source 'https://rubygems.org'

gem 'activerecord-oracle_enhanced-adapter'
gem 'activerecord'
gem 'builder'
gem 'byebug'
gem 'capybara-screenshot'
gem 'capybara'
gem 'command_line_reporter'
gem 'cucumber-rails'
gem 'cucumber'
gem 'factory_girl_rails'
gem 'factory_girl'
gem 'faker'
gem 'highline'
gem 'htmlentities'
gem 'launchy'
gem 'net-scp'
gem 'net-ssh'
gem 'parallel_tests'
gem 'pdf-reader'
gem 'rails'
gem 'rantly'
gem 'faraday'
gem 'rspec-rails'
gem 'rspec'
gem 'ruby-oci8','>= 2.2.2'
gem 'ruby-plsql-spec'
gem 'ruby-plsql'
gem 'selenium-webdriver', '2.47.1'
gem 'shoulda-matchers', :require => false
gem 'state_machine'
gem 'time_difference'
gem 'yarjuf'
gem 'factory-helper', '~> 1.7'